name: Publish to NPM

on:
  push:
    branches:
      - main
    paths:
      - 'packages/persona-sdk/package.json'
      - 'packages/prompt-optimizer/package.json'
  release:
    types: [created]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.10.0
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build packages
        run: pnpm build
      
      - name: Run tests
        run: pnpm test
      
      - name: Check if version changed
        id: version-check
        run: |
          if git diff HEAD^ HEAD --name-only | grep -qE "packages/(persona-sdk|prompt-optimizer)/package.json"; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi
  
  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && needs.test.outputs.version_changed == 'true')
    steps:
      - uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.10.0
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build packages
        run: pnpm build
        
      - name: Generate docs
        run: |
          cd packages/persona-sdk && DISPLAY= BROWSER=none pnpm docs
          cd ../prompt-optimizer && DISPLAY= BROWSER=none pnpm docs
      
      - name: Publish persona-sdk to npm
        run: npm publish --access public
        working-directory: ./packages/persona-sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Publish prompt-optimizer to npm
        run: npm publish --access public
        working-directory: ./packages/prompt-optimizer
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}